class EmanLocalization {
  const EmanLocalization(this.language);

  final String language;

  static const supported = ['en', 'tr', 'ar', 'es', 'pt', 'ru'];

  static const languageNames = {
    'en': 'English',
    'tr': 'Türkçe',
    'ar': 'العربية',
    'es': 'Español',
    'pt': 'Português',
    'ru': 'Русский',
  };

  String text(String key) {
    return _translations[language]?[key] ?? _translations['en']![key] ?? key;
  }

  static const _translations = <String, Map<String, String>>{
    'en': {
      'seoTitle': 'EMAN | International Food & Beverage Manufacturer',
      'topMessage': 'International food & beverage manufacturing',
      'globalMarkets': 'Serving global markets',
      'products': 'Products',
      'manufacturing': 'Manufacturing',
      'privateLabel': 'Private Label',
      'export': 'Export',
      'contact': 'Contact',
      'menu': 'Menu',
      'heroEyebrow': 'International beverage expertise',
      'heroTitle': 'Quality beverages. Made for the world.',
      'heroBody':
          'EMAN develops and manufactures reliable beverage solutions for distributors, retailers, wholesalers and private label partners.',
      'exploreProducts': 'Explore Products',
      'qualityAssured': 'Quality assured',
      'exportReady': 'Export ready',
      'heroMedia': 'EMAN product photography',
      'replaceableMedia': 'MEDIA SLOT · READY FOR OFFICIAL ASSET',
      'brandsEyebrow': 'Our brands',
      'brandsTitle': 'Distinct brands. One standard of quality.',
      'brandsBody':
          'A focused portfolio created for different consumers, channels and markets.',
      'logoPlaceholder': 'OFFICIAL LOGO SLOT',
      'productsEyebrow': 'Featured products',
      'productsTitle': 'Products designed for everyday demand.',
      'productsBody':
          'Flexible beverage formats with market-ready flavor profiles and dependable production.',
      'retailRange': 'Retail range',
      'singleServe': 'Single serve',
      'foodService': 'Food service',
      'productCitrus': 'Citrus collection',
      'productCitrusDetail': 'Bright, refreshing flavors for modern retail.',
      'productTropical': 'Tropical collection',
      'productTropicalDetail':
          'Convenient formats developed for easy preparation.',
      'productProfessional': 'Professional range',
      'productProfessionalDetail':
          'Reliable solutions for high-volume operators.',
      'productImagePlaceholder': 'OFFICIAL PRODUCT IMAGE',
      'manufacturingEyebrow': 'Manufacturing excellence',
      'manufacturingTitle': 'Precision at every stage.',
      'manufacturingBody':
          'From raw material control to final packing, our production approach is built around consistency, hygiene and dependable output.',
      'factoryMedia': 'Factory and production photography',
      'productionLines': 'Efficient production lines',
      'qualityControl': 'Quality control',
      'traceability': 'Batch traceability',
      'modernTechnology': 'Modern technology',
      'privateEyebrow': 'Partner solutions',
      'privateTitle': 'Your product. Our manufacturing expertise.',
      'privateBody':
          'A complete development and production service for partners building competitive beverage brands.',
      'oemBody':
          'Dependable contract manufacturing for established specifications.',
      'privateLabelBody':
          'Market-ready products presented under your own brand.',
      'customFormulation': 'Custom Formulation',
      'customFormulationBody':
          'Flavor and format development around your commercial brief.',
      'packagingSolutions': 'Packaging Solutions',
      'packagingSolutionsBody':
          'Practical packaging formats aligned with your channel.',
      'discussProject': 'Discuss Your Project',
      'exportEyebrow': 'International reach',
      'exportTitle': 'Built for global distribution.',
      'exportBody':
          'We support international partners with scalable supply, export coordination and market-focused product portfolios.',
      'markets': 'markets',
      'brands': 'brands',
      'flavors': 'flavors',
      'mapPlaceholder': 'Global distribution network',
      'certificationsEyebrow': 'Quality and compliance',
      'certificationsTitle': 'Standards our partners can trust.',
      'certificationsBody':
          'Certification assets can be added here without changing the approved layout.',
      'certificate': 'Certification',
      'certificatePlaceholder': 'Official certificate slot',
      'contactEyebrow': 'Contact EMAN',
      'contactTitle': 'Let’s build your next beverage opportunity.',
      'contactBody':
          'Tell us about your market, channel and requirements. Our commercial team will respond with the right next step.',
      'email': 'Email',
      'address': 'Address',
      'contactPending': 'Official details to be confirmed',
      'name': 'Name',
      'company': 'Company',
      'workEmail': 'Work email',
      'country': 'Country',
      'message': 'Tell us about your inquiry',
      'sendInquiry': 'Send Inquiry',
      'requiredField': 'This field is required',
      'validEmail': 'Enter a valid email address',
      'thankYou': 'Thank you for contacting EMAN.',
      'thankYouBody': 'Your inquiry has been prepared for our commercial team.',
      'footerText':
          'International food and beverage manufacturing for ambitious partners.',
      'rightsReserved': 'All rights reserved',
    },
    'tr': {
      'seoTitle': 'EMAN | Uluslararası Gıda ve İçecek Üreticisi',
      'topMessage': 'Uluslararası gıda ve içecek üretimi',
      'globalMarkets': 'Küresel pazarlara hizmet',
      'products': 'Ürünler',
      'manufacturing': 'Üretim',
      'privateLabel': 'Özel Marka',
      'export': 'İhracat',
      'contact': 'İletişim',
      'menu': 'Menü',
      'heroEyebrow': 'Uluslararası içecek uzmanlığı',
      'heroTitle': 'Kaliteli içecekler. Dünya için üretildi.',
      'heroBody':
          'EMAN; distribütörler, perakendeciler, toptancılar ve özel marka ortakları için güvenilir içecek çözümleri geliştirir ve üretir.',
      'exploreProducts': 'Ürünleri Keşfedin',
      'qualityAssured': 'Kalite güvencesi',
      'exportReady': 'İhracata hazır',
      'heroMedia': 'EMAN ürün fotoğrafı',
      'replaceableMedia': 'MEDYA ALANI · RESMÎ GÖRSEL İÇİN HAZIR',
      'brandsEyebrow': 'Markalarımız',
      'brandsTitle': 'Farklı markalar. Tek kalite standardı.',
      'brandsBody':
          'Farklı tüketiciler, kanallar ve pazarlar için oluşturulmuş odaklı bir portföy.',
      'logoPlaceholder': 'RESMÎ LOGO ALANI',
      'productsEyebrow': 'Öne çıkan ürünler',
      'productsTitle': 'Günlük talep için tasarlanan ürünler.',
      'productsBody':
          'Pazara hazır lezzet profilleri ve güvenilir üretimle esnek içecek formatları.',
      'retailRange': 'Perakende serisi',
      'singleServe': 'Tek porsiyon',
      'foodService': 'Yeme içme sektörü',
      'productCitrus': 'Narenciye koleksiyonu',
      'productCitrusDetail':
          'Modern perakende için canlı ve ferahlatıcı tatlar.',
      'productTropical': 'Tropikal koleksiyon',
      'productTropicalDetail':
          'Kolay hazırlama için geliştirilen pratik formatlar.',
      'productProfessional': 'Profesyonel seri',
      'productProfessionalDetail':
          'Yüksek hacimli işletmeler için güvenilir çözümler.',
      'productImagePlaceholder': 'RESMÎ ÜRÜN GÖRSELİ',
      'manufacturingEyebrow': 'Üretim mükemmelliği',
      'manufacturingTitle': 'Her aşamada hassasiyet.',
      'manufacturingBody':
          'Hammadde kontrolünden son paketlemeye kadar üretim yaklaşımımız tutarlılık, hijyen ve güvenilir çıktı üzerine kuruludur.',
      'factoryMedia': 'Fabrika ve üretim fotoğrafı',
      'productionLines': 'Verimli üretim hatları',
      'qualityControl': 'Kalite kontrolü',
      'traceability': 'Parti izlenebilirliği',
      'modernTechnology': 'Modern teknoloji',
      'privateEyebrow': 'İş ortağı çözümleri',
      'privateTitle': 'Sizin ürününüz. Bizim üretim uzmanlığımız.',
      'privateBody':
          'Rekabetçi içecek markaları oluşturan ortaklar için eksiksiz geliştirme ve üretim hizmeti.',
      'oemBody': 'Belirlenmiş özellikler için güvenilir fason üretim.',
      'privateLabelBody': 'Kendi markanızla sunulan pazara hazır ürünler.',
      'customFormulation': 'Özel Formülasyon',
      'customFormulationBody':
          'Ticari hedefinize göre lezzet ve format geliştirme.',
      'packagingSolutions': 'Ambalaj Çözümleri',
      'packagingSolutionsBody':
          'Satış kanalınıza uygun pratik ambalaj formatları.',
      'discussProject': 'Projenizi Görüşelim',
      'exportEyebrow': 'Uluslararası erişim',
      'exportTitle': 'Küresel dağıtım için hazır.',
      'exportBody':
          'Uluslararası ortaklarımızı ölçeklenebilir tedarik, ihracat koordinasyonu ve pazar odaklı ürün portföyleriyle destekliyoruz.',
      'markets': 'pazar',
      'brands': 'marka',
      'flavors': 'lezzet',
      'mapPlaceholder': 'Küresel dağıtım ağı',
      'certificationsEyebrow': 'Kalite ve uyum',
      'certificationsTitle': 'Ortaklarımızın güvenebileceği standartlar.',
      'certificationsBody':
          'Sertifika görselleri, onaylı düzen değişmeden buraya eklenebilir.',
      'certificate': 'Sertifika',
      'certificatePlaceholder': 'Resmî sertifika alanı',
      'contactEyebrow': 'EMAN ile iletişim',
      'contactTitle': 'Bir sonraki içecek fırsatınızı birlikte oluşturalım.',
      'contactBody':
          'Pazarınızı, kanalınızı ve ihtiyaçlarınızı anlatın. Ticari ekibimiz uygun sonraki adımla yanıt verecektir.',
      'email': 'E-posta',
      'address': 'Adres',
      'contactPending': 'Resmî bilgiler daha sonra eklenecek',
      'name': 'Ad Soyad',
      'company': 'Şirket',
      'workEmail': 'İş e-postası',
      'country': 'Ülke',
      'message': 'Talebinizi anlatın',
      'sendInquiry': 'Talep Gönder',
      'requiredField': 'Bu alan zorunludur',
      'validEmail': 'Geçerli bir e-posta adresi girin',
      'thankYou': 'EMAN ile iletişime geçtiğiniz için teşekkürler.',
      'thankYouBody': 'Talebiniz ticari ekibimiz için hazırlandı.',
      'footerText':
          'Hedefleri büyük ortaklar için uluslararası gıda ve içecek üretimi.',
      'rightsReserved': 'Tüm hakları saklıdır',
    },
    'ar': {
      'seoTitle': 'إيمان | مُصنّع دولي للأغذية والمشروبات',
      'topMessage': 'تصنيع دولي للأغذية والمشروبات',
      'globalMarkets': 'نخدم الأسواق العالمية',
      'products': 'المنتجات',
      'manufacturing': 'التصنيع',
      'privateLabel': 'العلامة الخاصة',
      'export': 'التصدير',
      'contact': 'اتصل بنا',
      'menu': 'القائمة',
      'heroEyebrow': 'خبرة دولية في المشروبات',
      'heroTitle': 'مشروبات عالية الجودة. صُنعت للعالم.',
      'heroBody':
          'تطوّر إيمان وتصنّع حلول مشروبات موثوقة للموزعين وتجار التجزئة والجملة وشركاء العلامات الخاصة.',
      'exploreProducts': 'استكشف المنتجات',
      'qualityAssured': 'جودة مضمونة',
      'exportReady': 'جاهز للتصدير',
      'heroMedia': 'صورة منتجات إيمان',
      'replaceableMedia': 'مساحة وسائط · جاهزة للصورة الرسمية',
      'brandsEyebrow': 'علاماتنا',
      'brandsTitle': 'علامات مميزة. معيار جودة واحد.',
      'brandsBody': 'محفظة مركزة صُممت لمستهلكين وقنوات وأسواق مختلفة.',
      'logoPlaceholder': 'مساحة الشعار الرسمي',
      'productsEyebrow': 'منتجات مختارة',
      'productsTitle': 'منتجات مصممة للطلب اليومي.',
      'productsBody': 'صيغ مشروبات مرنة بنكهات جاهزة للسوق وإنتاج موثوق.',
      'retailRange': 'مجموعة التجزئة',
      'singleServe': 'حصة فردية',
      'foodService': 'خدمات الطعام',
      'productCitrus': 'مجموعة الحمضيات',
      'productCitrusDetail': 'نكهات منعشة ومشرقة لتجارة التجزئة الحديثة.',
      'productTropical': 'المجموعة الاستوائية',
      'productTropicalDetail': 'صيغ عملية طُورت لسهولة التحضير.',
      'productProfessional': 'المجموعة الاحترافية',
      'productProfessionalDetail': 'حلول موثوقة للمشغلين ذوي الأحجام الكبيرة.',
      'productImagePlaceholder': 'صورة المنتج الرسمية',
      'manufacturingEyebrow': 'التميّز في التصنيع',
      'manufacturingTitle': 'دقة في كل مرحلة.',
      'manufacturingBody':
          'من مراقبة المواد الخام إلى التعبئة النهائية، يقوم نهجنا الإنتاجي على الثبات والنظافة والمخرجات الموثوقة.',
      'factoryMedia': 'صور المصنع والإنتاج',
      'productionLines': 'خطوط إنتاج فعّالة',
      'qualityControl': 'مراقبة الجودة',
      'traceability': 'تتبّع الدفعات',
      'modernTechnology': 'تقنية حديثة',
      'privateEyebrow': 'حلول الشركاء',
      'privateTitle': 'منتجك. خبرتنا في التصنيع.',
      'privateBody':
          'خدمة تطوير وإنتاج متكاملة للشركاء الذين يبنون علامات مشروبات تنافسية.',
      'oemBody': 'تصنيع تعاقدي موثوق للمواصفات المعتمدة.',
      'privateLabelBody': 'منتجات جاهزة للسوق تحمل علامتك التجارية.',
      'customFormulation': 'تركيبة مخصصة',
      'customFormulationBody': 'تطوير النكهة والصيغة وفق أهدافك التجارية.',
      'packagingSolutions': 'حلول التعبئة',
      'packagingSolutionsBody': 'صيغ تعبئة عملية تناسب قناة البيع الخاصة بك.',
      'discussProject': 'ناقش مشروعك',
      'exportEyebrow': 'انتشار دولي',
      'exportTitle': 'جاهزون للتوزيع العالمي.',
      'exportBody':
          'ندعم شركاءنا الدوليين بإمداد قابل للتوسع وتنسيق التصدير ومحافظ منتجات تركز على السوق.',
      'markets': 'سوقاً',
      'brands': 'علامات',
      'flavors': 'نكهة',
      'mapPlaceholder': 'شبكة توزيع عالمية',
      'certificationsEyebrow': 'الجودة والامتثال',
      'certificationsTitle': 'معايير يثق بها شركاؤنا.',
      'certificationsBody':
          'يمكن إضافة صور الشهادات هنا دون تغيير التصميم المعتمد.',
      'certificate': 'شهادة',
      'certificatePlaceholder': 'مساحة الشهادة الرسمية',
      'contactEyebrow': 'تواصل مع إيمان',
      'contactTitle': 'لنصنع فرصة مشروباتك القادمة.',
      'contactBody':
          'أخبرنا عن سوقك وقناتك ومتطلباتك. سيرد فريقنا التجاري بالخطوة المناسبة.',
      'email': 'البريد الإلكتروني',
      'address': 'العنوان',
      'contactPending': 'ستُضاف البيانات الرسمية لاحقاً',
      'name': 'الاسم',
      'company': 'الشركة',
      'workEmail': 'بريد العمل',
      'country': 'الدولة',
      'message': 'أخبرنا عن طلبك',
      'sendInquiry': 'إرسال الطلب',
      'requiredField': 'هذا الحقل مطلوب',
      'validEmail': 'أدخل بريداً إلكترونياً صالحاً',
      'thankYou': 'شكراً لتواصلك مع إيمان.',
      'thankYouBody': 'تم إعداد طلبك لفريقنا التجاري.',
      'footerText': 'تصنيع دولي للأغذية والمشروبات لشركاء طموحين.',
      'rightsReserved': 'جميع الحقوق محفوظة',
    },
    'es': {
      'seoTitle': 'EMAN | Fabricante internacional de alimentos y bebidas',
      'topMessage': 'Fabricación internacional de alimentos y bebidas',
      'globalMarkets': 'Presentes en mercados globales',
      'products': 'Productos',
      'manufacturing': 'Fabricación',
      'privateLabel': 'Marca Privada',
      'export': 'Exportación',
      'contact': 'Contacto',
      'menu': 'Menú',
      'heroEyebrow': 'Experiencia internacional en bebidas',
      'heroTitle': 'Bebidas de calidad. Hechas para el mundo.',
      'heroBody':
          'EMAN desarrolla y fabrica soluciones confiables para distribuidores, supermercados, mayoristas y socios de marca privada.',
      'exploreProducts': 'Explorar Productos',
      'qualityAssured': 'Calidad garantizada',
      'exportReady': 'Listos para exportar',
      'heroMedia': 'Fotografía de productos EMAN',
      'replaceableMedia': 'ESPACIO MULTIMEDIA · LISTO PARA RECURSO OFICIAL',
      'brandsEyebrow': 'Nuestras marcas',
      'brandsTitle': 'Marcas distintas. Un estándar de calidad.',
      'brandsBody':
          'Un portafolio enfocado para diferentes consumidores, canales y mercados.',
      'logoPlaceholder': 'ESPACIO PARA LOGO OFICIAL',
      'productsEyebrow': 'Productos destacados',
      'productsTitle': 'Productos diseñados para la demanda diaria.',
      'productsBody':
          'Formatos flexibles con perfiles de sabor listos para el mercado y producción confiable.',
      'retailRange': 'Línea minorista',
      'singleServe': 'Porción individual',
      'foodService': 'Servicio de alimentos',
      'productCitrus': 'Colección cítrica',
      'productCitrusDetail':
          'Sabores vivos y refrescantes para el comercio moderno.',
      'productTropical': 'Colección tropical',
      'productTropicalDetail':
          'Formatos prácticos desarrollados para una preparación fácil.',
      'productProfessional': 'Línea profesional',
      'productProfessionalDetail':
          'Soluciones confiables para operadores de gran volumen.',
      'productImagePlaceholder': 'IMAGEN OFICIAL DEL PRODUCTO',
      'manufacturingEyebrow': 'Excelencia en fabricación',
      'manufacturingTitle': 'Precisión en cada etapa.',
      'manufacturingBody':
          'Desde el control de materias primas hasta el empaque final, producimos con consistencia, higiene y resultados confiables.',
      'factoryMedia': 'Fotografía de fábrica y producción',
      'productionLines': 'Líneas de producción eficientes',
      'qualityControl': 'Control de calidad',
      'traceability': 'Trazabilidad por lote',
      'modernTechnology': 'Tecnología moderna',
      'privateEyebrow': 'Soluciones para socios',
      'privateTitle': 'Su producto. Nuestra experiencia de fabricación.',
      'privateBody':
          'Un servicio completo de desarrollo y producción para crear marcas competitivas.',
      'oemBody':
          'Fabricación por contrato confiable para especificaciones establecidas.',
      'privateLabelBody':
          'Productos listos para el mercado con su propia marca.',
      'customFormulation': 'Formulación Personalizada',
      'customFormulationBody':
          'Desarrollo de sabor y formato según su objetivo comercial.',
      'packagingSolutions': 'Soluciones de Empaque',
      'packagingSolutionsBody': 'Formatos prácticos alineados con su canal.',
      'discussProject': 'Hablemos de su Proyecto',
      'exportEyebrow': 'Alcance internacional',
      'exportTitle': 'Preparados para la distribución global.',
      'exportBody':
          'Apoyamos a socios internacionales con suministro escalable, coordinación de exportación y portafolios orientados al mercado.',
      'markets': 'mercados',
      'brands': 'marcas',
      'flavors': 'sabores',
      'mapPlaceholder': 'Red de distribución global',
      'certificationsEyebrow': 'Calidad y cumplimiento',
      'certificationsTitle': 'Estándares en los que nuestros socios confían.',
      'certificationsBody':
          'Los certificados pueden añadirse aquí sin modificar el diseño aprobado.',
      'certificate': 'Certificación',
      'certificatePlaceholder': 'Espacio para certificado oficial',
      'contactEyebrow': 'Contacte con EMAN',
      'contactTitle': 'Construyamos su próxima oportunidad.',
      'contactBody':
          'Cuéntenos sobre su mercado, canal y requisitos. Nuestro equipo comercial responderá con el siguiente paso.',
      'email': 'Correo electrónico',
      'address': 'Dirección',
      'contactPending': 'Datos oficiales pendientes',
      'name': 'Nombre',
      'company': 'Empresa',
      'workEmail': 'Correo de trabajo',
      'country': 'País',
      'message': 'Cuéntenos sobre su consulta',
      'sendInquiry': 'Enviar Consulta',
      'requiredField': 'Este campo es obligatorio',
      'validEmail': 'Introduzca un correo válido',
      'thankYou': 'Gracias por contactar con EMAN.',
      'thankYouBody':
          'Su consulta está preparada para nuestro equipo comercial.',
      'footerText': 'Fabricación internacional para socios ambiciosos.',
      'rightsReserved': 'Todos los derechos reservados',
    },
    'pt': {
      'seoTitle': 'EMAN | Fabricante internacional de alimentos e bebidas',
      'topMessage': 'Fabricação internacional de alimentos e bebidas',
      'globalMarkets': 'Atendendo mercados globais',
      'products': 'Produtos',
      'manufacturing': 'Fabricação',
      'privateLabel': 'Marca Própria',
      'export': 'Exportação',
      'contact': 'Contato',
      'menu': 'Menu',
      'heroEyebrow': 'Experiência internacional em bebidas',
      'heroTitle': 'Bebidas de qualidade. Feitas para o mundo.',
      'heroBody':
          'A EMAN desenvolve e fabrica soluções confiáveis para distribuidores, supermercados, atacadistas e parceiros de marca própria.',
      'exploreProducts': 'Explorar Produtos',
      'qualityAssured': 'Qualidade garantida',
      'exportReady': 'Pronto para exportar',
      'heroMedia': 'Fotografia de produtos EMAN',
      'replaceableMedia': 'ESPAÇO DE MÍDIA · PRONTO PARA ARQUIVO OFICIAL',
      'brandsEyebrow': 'Nossas marcas',
      'brandsTitle': 'Marcas distintas. Um padrão de qualidade.',
      'brandsBody':
          'Um portfólio focado em diferentes consumidores, canais e mercados.',
      'logoPlaceholder': 'ESPAÇO PARA LOGO OFICIAL',
      'productsEyebrow': 'Produtos em destaque',
      'productsTitle': 'Produtos criados para a demanda diária.',
      'productsBody':
          'Formatos flexíveis com sabores prontos para o mercado e produção confiável.',
      'retailRange': 'Linha de varejo',
      'singleServe': 'Porção individual',
      'foodService': 'Food service',
      'productCitrus': 'Coleção cítrica',
      'productCitrusDetail':
          'Sabores vivos e refrescantes para o varejo moderno.',
      'productTropical': 'Coleção tropical',
      'productTropicalDetail':
          'Formatos práticos desenvolvidos para preparo fácil.',
      'productProfessional': 'Linha profissional',
      'productProfessionalDetail':
          'Soluções confiáveis para operações de alto volume.',
      'productImagePlaceholder': 'IMAGEM OFICIAL DO PRODUTO',
      'manufacturingEyebrow': 'Excelência em fabricação',
      'manufacturingTitle': 'Precisão em todas as etapas.',
      'manufacturingBody':
          'Do controle da matéria-prima à embalagem final, produzimos com consistência, higiene e resultados confiáveis.',
      'factoryMedia': 'Fotografia da fábrica e produção',
      'productionLines': 'Linhas de produção eficientes',
      'qualityControl': 'Controle de qualidade',
      'traceability': 'Rastreabilidade por lote',
      'modernTechnology': 'Tecnologia moderna',
      'privateEyebrow': 'Soluções para parceiros',
      'privateTitle': 'Seu produto. Nossa experiência em fabricação.',
      'privateBody':
          'Serviço completo de desenvolvimento e produção para marcas competitivas.',
      'oemBody':
          'Fabricação por contrato confiável para especificações definidas.',
      'privateLabelBody': 'Produtos prontos para o mercado com a sua marca.',
      'customFormulation': 'Formulação Personalizada',
      'customFormulationBody':
          'Desenvolvimento de sabor e formato conforme seu objetivo.',
      'packagingSolutions': 'Soluções de Embalagem',
      'packagingSolutionsBody': 'Formatos práticos alinhados ao seu canal.',
      'discussProject': 'Fale sobre seu Projeto',
      'exportEyebrow': 'Alcance internacional',
      'exportTitle': 'Preparados para distribuição global.',
      'exportBody':
          'Apoiamos parceiros internacionais com fornecimento escalável, coordenação de exportação e portfólios focados no mercado.',
      'markets': 'mercados',
      'brands': 'marcas',
      'flavors': 'sabores',
      'mapPlaceholder': 'Rede global de distribuição',
      'certificationsEyebrow': 'Qualidade e conformidade',
      'certificationsTitle': 'Padrões em que nossos parceiros confiam.',
      'certificationsBody':
          'Os certificados podem ser adicionados aqui sem alterar o layout aprovado.',
      'certificate': 'Certificação',
      'certificatePlaceholder': 'Espaço para certificado oficial',
      'contactEyebrow': 'Contato EMAN',
      'contactTitle': 'Vamos criar sua próxima oportunidade.',
      'contactBody':
          'Conte sobre seu mercado, canal e requisitos. Nossa equipe comercial responderá com o próximo passo.',
      'email': 'E-mail',
      'address': 'Endereço',
      'contactPending': 'Dados oficiais a confirmar',
      'name': 'Nome',
      'company': 'Empresa',
      'workEmail': 'E-mail profissional',
      'country': 'País',
      'message': 'Conte sobre sua consulta',
      'sendInquiry': 'Enviar Consulta',
      'requiredField': 'Este campo é obrigatório',
      'validEmail': 'Insira um e-mail válido',
      'thankYou': 'Obrigado por contatar a EMAN.',
      'thankYouBody': 'Sua consulta está pronta para nossa equipe comercial.',
      'footerText':
          'Fabricação internacional de alimentos e bebidas para parceiros ambiciosos.',
      'rightsReserved': 'Todos os direitos reservados',
    },
    'ru': {
      'seoTitle': 'EMAN | Международный производитель продуктов и напитков',
      'topMessage': 'Международное производство продуктов и напитков',
      'globalMarkets': 'Работаем на мировых рынках',
      'products': 'Продукция',
      'manufacturing': 'Производство',
      'privateLabel': 'Частная Марка',
      'export': 'Экспорт',
      'contact': 'Контакты',
      'menu': 'Меню',
      'heroEyebrow': 'Международная экспертиза в напитках',
      'heroTitle': 'Качественные напитки. Созданы для мира.',
      'heroBody':
          'EMAN разрабатывает и производит надежные решения для дистрибьюторов, розничных сетей, оптовиков и партнеров частных марок.',
      'exploreProducts': 'Смотреть Продукцию',
      'qualityAssured': 'Гарантия качества',
      'exportReady': 'Готово к экспорту',
      'heroMedia': 'Фотография продукции EMAN',
      'replaceableMedia': 'МЕДИАБЛОК · ГОТОВ ДЛЯ ОФИЦИАЛЬНОГО ФАЙЛА',
      'brandsEyebrow': 'Наши бренды',
      'brandsTitle': 'Разные бренды. Единый стандарт качества.',
      'brandsBody':
          'Сфокусированный портфель для разных потребителей, каналов и рынков.',
      'logoPlaceholder': 'МЕСТО ДЛЯ ОФИЦИАЛЬНОГО ЛОГОТИПА',
      'productsEyebrow': 'Избранная продукция',
      'productsTitle': 'Продукты для ежедневного спроса.',
      'productsBody':
          'Гибкие форматы, готовые вкусовые профили и надежное производство.',
      'retailRange': 'Розничная линейка',
      'singleServe': 'Одна порция',
      'foodService': 'Общественное питание',
      'productCitrus': 'Цитрусовая коллекция',
      'productCitrusDetail': 'Яркие освежающие вкусы для современной розницы.',
      'productTropical': 'Тропическая коллекция',
      'productTropicalDetail': 'Удобные форматы для простого приготовления.',
      'productProfessional': 'Профессиональная линейка',
      'productProfessionalDetail': 'Надежные решения для крупных операторов.',
      'productImagePlaceholder': 'ОФИЦИАЛЬНОЕ ФОТО ПРОДУКТА',
      'manufacturingEyebrow': 'Совершенство производства',
      'manufacturingTitle': 'Точность на каждом этапе.',
      'manufacturingBody':
          'От контроля сырья до упаковки наш подход основан на стабильности, гигиене и надежном результате.',
      'factoryMedia': 'Фотографии завода и производства',
      'productionLines': 'Эффективные линии',
      'qualityControl': 'Контроль качества',
      'traceability': 'Прослеживаемость партий',
      'modernTechnology': 'Современные технологии',
      'privateEyebrow': 'Решения для партнеров',
      'privateTitle': 'Ваш продукт. Наша производственная экспертиза.',
      'privateBody':
          'Полный цикл разработки и производства конкурентоспособных брендов напитков.',
      'oemBody': 'Надежное контрактное производство по готовым спецификациям.',
      'privateLabelBody': 'Готовые продукты под вашей торговой маркой.',
      'customFormulation': 'Индивидуальная Рецептура',
      'customFormulationBody':
          'Разработка вкуса и формата под коммерческие задачи.',
      'packagingSolutions': 'Решения по Упаковке',
      'packagingSolutionsBody': 'Практичные форматы для вашего канала продаж.',
      'discussProject': 'Обсудить Проект',
      'exportEyebrow': 'Международный охват',
      'exportTitle': 'Создано для мировой дистрибуции.',
      'exportBody':
          'Мы поддерживаем партнеров масштабируемыми поставками, координацией экспорта и рыночными портфелями.',
      'markets': 'рынков',
      'brands': 'бренда',
      'flavors': 'вкусов',
      'mapPlaceholder': 'Глобальная сеть дистрибуции',
      'certificationsEyebrow': 'Качество и соответствие',
      'certificationsTitle': 'Стандарты, которым доверяют партнеры.',
      'certificationsBody':
          'Сертификаты можно добавить сюда без изменения утвержденной верстки.',
      'certificate': 'Сертификат',
      'certificatePlaceholder': 'Место для официального сертификата',
      'contactEyebrow': 'Связаться с EMAN',
      'contactTitle': 'Создадим вашу следующую возможность.',
      'contactBody':
          'Расскажите о рынке, канале и требованиях. Коммерческая команда предложит следующий шаг.',
      'email': 'Эл. почта',
      'address': 'Адрес',
      'contactPending': 'Официальные данные будут добавлены',
      'name': 'Имя',
      'company': 'Компания',
      'workEmail': 'Рабочая эл. почта',
      'country': 'Страна',
      'message': 'Расскажите о запросе',
      'sendInquiry': 'Отправить Запрос',
      'requiredField': 'Обязательное поле',
      'validEmail': 'Введите корректный адрес',
      'thankYou': 'Спасибо за обращение в EMAN.',
      'thankYouBody': 'Ваш запрос подготовлен для коммерческой команды.',
      'footerText':
          'Международное производство продуктов и напитков для амбициозных партнеров.',
      'rightsReserved': 'Все права защищены',
    },
  };
}
